### ISSUE TITLE
index out of range bug

### ISSUE THREAD

**Issue by MegaByte32** [MegaByte32/PassKeyGen#1]
Traceback (most recent call last): File "K:\MegaByte\passFounder.py", line 45, in Founder() File "K:\MegaByte\passFounder.py", line 28, in Founder passW = passW + (txt_Int[txt]) IndexError: list index out of range

*This is the error I get when the program runs the third selection. That being said it doesn't always happen.*

**Comment by Soliman2020** [comment]
Plz check my fork, as I did some code changes and now the mentioned issue is not running again.

**Comment by MegaByte32** [comment]
> Plz check my fork, as I did some code changes and now the mentioned issue is not running again.

Thank you so much! I've been trying to refresh myself on python so this was really helpful!
